version: '3'

networks:
  graph-net:

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file: .env #Файл, где находятся настройки в виде переменных среды
    depends_on:
      - mysql
    ports:
      - 8181:80
    environment:
      PMA_HOST: mysql
      MYSQL_USERNAME: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - graph-net

  mysql:
    image: mysql:5.7
    env_file: .env #Файл, где находятся настройки в виде переменных среды
    command: mysqld --innodb-use-native-aio=0 --character-set-server=utf8 --collation-server=utf8_general_ci --init-connect='SET NAMES UTF8;'
    environment:
      - MYSQL_DATABASE=${DB_DATABASE} #Имя базы данных
      - MYSQL_PASSWORD=${DB_PASSWORD} #Не-root пароль для пользователя ${DB_USERNAME}
      - MYSQL_USER=${DB_USERNAME} #Логин не-root пользователя
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-proot" ]
      timeout: 20s
      retries: 10
    ports:
      - "3310:3306"
      - "33069:33060"
    volumes:
      - ./docker/mysql/db:/var/lib/mysql
    networks:
      - graph-net

  nginx:
    build: docker/nginx
    stdin_open: true
    depends_on:
      - php-fpm
    ports:
      - "1010:1000"
    volumes: # Передает кофигурацию для веб-сервера
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www
    networks:
      - graph-net

  php-fpm:
    build: docker/php_fpm
    env_file: .env
    depends_on:
      - mysql
    environment:
      APP_DEBUG: ${APP_DEBUG}
      DB_HOST: crud_mysql
      DB_PORT: ${DB_PORT} #Порт подключения к базе данных
      DB_DATABASE: ${DB_DATABASE} #Имя базы данных
      DB_USERNAME: ${DB_USERNAME} #Имя пользователя для подключения к базе данных
      DB_PASSWORD: ${DB_PASSWORD} #Пароль для подключения к базе данных
    stdin_open: true
    volumes:
      - ./src:/var/www
    networks:
      - graph-net


